net:
  ironoc:
    portfolio:
      github:
        timeout:
          connect: 100000
          read: 100000
        instance-follow-redirects: true
        follow-redirects: true
        api:
          endpoint:
            repos: https://api.github.com/users/{username}/repos?per_page={per_page}&page={page}
            issues: https://api.github.com/repos/{username}/{repo}/issues?per_page={per_page}&page={page}

spring:
  mvc:
    favicon:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-ironoc.html
    operationsSorter: method
