com:
  ironoc:
    portfolio:
      github:
        timeout:
          connect: 100000
          read: 100000
        instance-follow-redirects: true
        follow-redirects: true
        api:
          endpoint: https://api.github.com/users/{username}/repos

spring:
  mvc:
    favicon:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-ironoc.html
    operationsSorter: method
