# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: './frontend'
      - run: npm test
        working-directory: './frontend'

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # registry-url: https://npm.pkg.github.com/
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: './frontend'
      - run: npm set "//registry.npmjs.org/conorheffron/:_authToken=$NPM_TOKEN"
        env: 
          NPM_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - run: npm publish
        working-directory: './frontend'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
